device:
  zoef:
    type: zoef_pcb
    samping_interval: 10
distance:
  left:
    name: left
    device: zoef
    connector: SRF2
  right:
    name: right
    device: zoef
    connector: SRF1
encoder:
  left:
    name: left
    device: zoef
    connector: ENCB
    ticks_per_wheel: 20
  right:
    name: right
    device: zoef
    connector: ENCA
    ticks_per_wheel: 20
intensity:
  left:
    name: left 
    device: zoef
    connector: IR2
#    max_frequency: 100
  right:
    name: right
    device: zoef
    connector: IR1
#oled:
#  left_oled:
#    device: zoef
#    connector: I2C2
#  right_oled:
#    device: zoef
#    connector: I2C1
#led:
#  device: zoef
#  connector: LED
#servo:
#  device: zoef
#  connector: SERVO
keypad:
  yellow:
    name: keypad
    device: zoef
    connector: KEY
motor:
  left:
    name: left
    device: zoef
    connector: MB
  right:
    name: right
    device: zoef
    connector: MA
#left_motor: left_motor
#right_motor: right_motor
#wheel_radius: 0.065
#wheel_seperation: 0.13
