device:
  zoef:
    type: breadboard
    mcu: stm32
    samping_interval: 10
distance:
  left_distance:
    device: zoef
    pins:
      trigger: A9
      echo: B8
  right_distance:
    device: zoef
    pins:
      trigger: A10
      echo: B9
encoder:
  left_encoder:
    device: zoef
    pins:
      pin: B12           # pin needs interrupt support
    ticks_per_wheel: 20
  right_encoder:
    device: zoef
    pins:
      pin: B13           # pin needs interrupt support
    ticks_per_wheel: 20
intensity:
  left_intensity: 
    device: zoef
    pins:
      digital: B1
      analog: A0         # pin needs analog input
  right_intensity:
    device: zoef
    pins:
      digital: B0
      analog: A1         # pin needs analog input
oled:
  left_oled:
    device: zoef
    pins:
      scl: B6
      sda: B7
  right_oled:
    device: zoef
    pins:
      scl: B10
      sca: B11
led:
  device: zoef
  pins:
    pin: B4                # pin needs PWM
servo:
  device: zoef
  pins:
    pin: B5                # pin needs PWM
keypad:
  device: zoef
  pins:
    pin: A4                # pin needs analog input
motor:
  left_motor:
    device: zoef
    pins:
      1a: A8             # pin needs PWM
      1b: B3             # pin needs PWM
  right_motor:
    device: zoef
    pins:
      1a: B14            # pin needs PWM
      1b: B15            # pin needs PWM
#left_motor: left_motor
#right_motor: right_motor
#wheel_radius: 0.065
#wheel_seperation: 0.13
