device:
  zoef:
    type: zoef_pcb
    samping_interval: 10
distance:
  left_distance:
    device: zoef
    connector: SRF1
  right_distance:
    device: zoef
    connector: SRF2
encoder:
  left_encoder:
    device: zoef
    connector: ENCA
    ticks_per_wheel: 20
  right_encoder:
    device: zoef
    connector: ENCB
    ticks_per_wheel: 20
intensity:
  left_intensity: 
    device: zoef
    connector: IR1
  right_intensity:
    device: zoef
    connector: IR2
oled:
  left_oled:
    device: zoef
    connector: I2C1
  right_oled:
    device: zoef
    connector: I2C2
led:
  device: zoef
  connector: LED
servo:
  device: zoef
  connector: SERVO
keypad:
  device: zoef
  connector: KEY
motor:
  left_motor:
    device: zoef
    connector: MB
  right_motor:
    device: zoef
    connector: MA
#left_motor: left_motor
#right_motor: right_motor
#wheel_radius: 0.065
#wheel_seperation: 0.13
