device:
  zoef:
    type: zoef
    dev: "/dev/ttyUSB0"
distance:
  left_distance:
    device: zoef
    frequency: 10
    pin: [10, 12]   #D10 (trigger), D12 (echo)
#  right_distance:   # BUG: needds to be connected to a digital pin!
#    device: zoef
#    frequency: 10
#    pin: [0, 13]
encoder:
  left_encoder: {device: zoef, pin: 2, ticks_per_wheel: 20}  #No frequency, since it is an interrupt
  right_encoder: {device: zoef, pin: 3, ticks_per_wheel: 20}
#intensity:
#  left_intensity: {device: zoef, frequency: 10, pin: 1} #NOTE: A1
#  right_intensity: {device: zoef, frequency: 10, pin: 2} #NOTE: A2 
motor:
  left_motor:
    device: zoef
    pin: [7, 8, 9]  #D7, D8, D9 (PWM)
  right_motor:
    device: zoef
    pin: [4, 5, 6]  #D4, D5, D6 (PWM)
left_motor: left_motor
right_motor: right_motor
wheel_radius: 0.065
wheel_seperation: 0.13
