device:
  zoef:
    type: zoef
    dev: "/dev/ttyACM0"
#    samping_interval: 10   TODO, hardcoded in pymata.py
distance:
  left_distance:
    device: zoef
#    frequency: 10  currently not used
    pin: [11, 1]    #SRF1, A9 (trigger), B8 (echo)
  right_distance:
    device: zoef
#    frequency: 10  currently not used
    pin: [10, 0]    #SRF2, A10 (trigger), B9 (echo)
encoder:
  left_encoder:     #No frequency, since it is an interrupt
    device: zoef
    pin: 16         #EN1, B12 (interrupt)
    ticks_per_wheel: 20
  right_encoder:    #No frequency, since it is an interrupt
    device: zoef
    pin: 15         #EN2, B13 (interrupt)
    ticks_per_wheel: 20
intensity:
  left_intensity: 
    device: zoef
#    frequency: 100 currently not used
    pin: 0          #NOTE, ANALOG 0. IR1, A0 (currently not using digital pin A12)
  right_intensity:
    device: zoef
#    frequency: 10 currently not used
    pin: 1          #NOTE, ANALOG 1, IR2, A1 (currently not using digital pin A11)
led:
  pin: 5            # B4
motor:
#  type: MX1919      #TODO: make possbile to run MX1919 with 5V and L298N with 12V, currently on nr of pins
  left_motor:
    device: zoef
    pin: [14, 13]   #M1, B14 (PWM), B15 (PWM)
    #pin: [7, 8, 9]   #M1, D7, D8, D9 (PWM, EN)
  right_motor:
    device: zoef
    pin: [7, 6]     #M2, A15 (PWM), B3 (PWM)
    #pin: [4, 5, 6]   #M2, D4, D5, D6 (PWM, EN)
left_motor: left_motor
right_motor: right_motor
#wheel_radius: 0.065
#wheel_seperation: 0.13
