device:
  zoef:
    type: zoef
    dev: "/dev/ttyACM0"
distance:
  left_distance:
    device: zoef
    frequency: 10
    pin: [11, 1]    #SRF1, A9 (trigger), B8 (echo)
  right_distance:
    device: zoef
    frequency: 10
    pin: [10, 0]    #SRF2, A10 (trigger), B9 (echo)
encoder:
  left_encoder:     #No frequency, since it is an interrupt
    device: zoef
    pin: 16         #EN1, B12 (interrupt)
    ticks_per_wheel: 20
  right_encoder:    #No frequency, since it is an interrupt
    device: zoef
    pin: 15         #EN2, B13 (interrupt)
    ticks_per_wheel: 20
intensity:
  left_intensity: 
    device: zoef
    frequency: 100
    pin: 0          #NOTE, ANALOG 0. IR1, A0 (currently not using digital pin A12)
  right_intensity:
    device: zoef
    frequency: 10
    pin: 1          #NOTE, ANALOG 1, IR2, A1 (currently not using digital pin A11)
motor:
  #type: MX1919      #TODO: make possbile to run MX1919 with 5V and L298N with 12V, currently on nr of pins
  left_motor:
    device: zoef
    pin: [14, 13]   #M1, B14 (PWM), B15 (PWM)
  right_motor:
    device: zoef
    pin: [7, 6]     #M2, A15 (PWM), B3 (PWM)
left_motor: left_motor
right_motor: right_motor
#wheel_radius: 0.065
#wheel_seperation: 0.13
