device:
  zoef:
    type: breadboard
    mcu: nano
    samping_interval: 10
distance:
  left_distance:
    device: zoef
    pins:
      trigger: A3
      echo: A4
  right_distance:
    device: zoef
    pins:
      trigger: A5
      echo: A6
encoder:
  left_encoder:
    device: zoef
    pins:
      pin: D2            # pin needs interrupt support
    ticks_per_wheel: 20
  right_encoder:
    device: zoef
    pins:
      pin: D3            # pin needs interrupt support
    ticks_per_wheel: 20
intensity:
  left_intensity: 
    device: zoef
    pins:
      digital: D7
      analog: A0         # pin needs analog input
  right_intensity:
    device: zoef
    pins:
      digital: D8
      analog: A1         # pin needs analog input
oled:
  left_oled:
    device: zoef
    pins:
      scl: A5
      sda: A4
servo:
  device: zoef
  pins:
    pin: D11               # pin needs PWM
keypad:
  device: zoef
  pins:
    pin: A2                # pin needs analog input
motor:
  left_motor:
    device: zoef
    pins:
      1a: D5               # pin needs PWM
      1b: D6               # pin needs PWM
  right_motor:
    device: zoef
    pins:
      1a: D9               # pin needs PWM
      1b: D10              # pin needs PWM
#left_motor: left_motor
#right_motor: right_motor
#wheel_radius: 0.065
#wheel_seperation: 0.13
