device:
  mirte:
    type: mirte_pcb
    samping_interval: 10
distance:
#  left:
#    name: left
#    device: mirte
#    connector: SRF2
  right:
    name: right
    device: mirte
    connector: SRF1
encoder:
  left:
    name: left
    device: mirte
    connector: ENCB
    ticks_per_wheel: 20
  right:
    name: right
    device: mirte
    connector: ENCA
    ticks_per_wheel: 20
intensity:
  left:
    name: left 
    device: mirte
    connector: IR2
  right:
    name: right
    device: mirte
    connector: IR1
#oled:
#  left:
#    name: left
#    device: mirte
#    connector: I2C2
#  right:
#    name: right
#    device: mirte
#    connector: I2C1
led:
  device: mirte
  connector: LED
servo:
  device: mirte
  connector: SERVO
keypad:
  yellow:
    name: keypad
    device: mirte
    connector: KEY
motor:
  left:
    name: left
    device: mirte
    connector: MB
  right:
    name: right
    device: mirte
    connector: MA
#left_motor: left_motor
#right_motor: right_motor
#wheel_radius: 0.065
#wheel_seperation: 0.13
