device:
  mirte:
    type: breadboard
    mcu: mega
    max_frequency: 100

motor:
  leftfront:
    name: leftfront
    device: mirte
    type: l9110s
    pins:
      1a: 4             # pin needs PWM
      1b: 6             # pin needs PWM
  rightfront:
    name: rightfront
    device: mirte
    type: l9110s
    pins:
      1a: 11            # pin needs PWM
      1b: 9            # pin needs PWM
  leftrear:
    name: leftrear
    device: mirte
    type: l9110s
    pins:
      1a: 7             # pin needs PWM
      1b: 5             # pin needs PWM
  rightrear:
    name: rightrear
    device: mirte
    type: l9110s
    pins:
      1a: 10            # pin needs PWM
      1b: 8            # pin needs PWM

encoder:
  leftfront:
    name: leftfront
    device: mirte
    pins:
      pin: 18           # pin needs interrupt support
    ticks_per_wheel: 20
  rightfront:
    name: rightfront
    device: mirte
    pins:
      pin: 19           # pin needs interrupt support
    ticks_per_wheel: 20
  leftrear:
    name: leftrear
    device: mirte
    pins:
      pin: 20           # pin needs interrupt support
    ticks_per_wheel: 20
  rightrear:
    name: rightrear
    device: mirte
    pins:
      pin: 21           # pin needs interrupt support
    ticks_per_wheel: 20
      # 18 14
      # 19 15
      # 20 16
      # 21 17