device:
  mirte:
    type: breadboard
    mcu: pico
    max_frequency: 10
distance:
  left:
    name: left
    device: mirte
    pins:
      trigger: 7
      echo: 6
encoder:
  left:
    name: left
    device: mirte
    pins:
      1a: 18             # pin needs PWM
      1b: 19             # pin needs PWM
  right:
    name: right
    device: mirte
    pins:
      1a: 20            # pin needs PWM
      1b: 21            # pin needs PWM
